---

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Description: "Simple pet shop backend using Lambda + API Gateway"

Resources:
  #
  # API Gateway
  #
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: pet-shop-api.yaml
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref LambdaFunction

  #
  # Lambda
  #
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: index.handler
      Runtime: nodejs6.10
      Role: !GetAtt LambdaPetStoreRole.Arn
      Environment:
        Variables:
          TABLE_NAME:
            !Ref DDBTable
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

  LambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ApiGatewayApi
      - LambdaFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com

  #
  # DynamoDB Table
  #
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: uuid
          AttributeType: S
      KeySchema:
        -
          AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "my-pet-shop"

  #
  # IAM
  # 
  LambdaPetStoreRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowLambdaServiceToAssumeRole
            Effect: Allow
            Action: 
              - sts:AssumeRole
            Principal:
              Service: 
                - lambda.amazonaws.com

  LambdaRWDDBPolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaPetStoreRole
    Properties:
      PolicyName: LambdaPetStorePolicy
      Roles:
        - !Ref LambdaPetStoreRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          -
            Effect:   "Allow"
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/my-pet-shop"
            Action:
              - "dynamodb:DeleteItem"
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
              - "dynamodb:Scan"
              - "dynamodb:UpdateItem"

Outputs:
  ApiUrl:
    Description: API Endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'
